eureka:
  instance:
    hostname: scissor-servers.onrender.com
  
  client:
    register-with-eureka: false
    fetch-registry: false

# default for eureka server
server:
  port: 8761
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: "alway
  logging:
    level:
      root: DEBUG
      org.springframework.web: DEBUG
      com.netflix.eureka: DEBUG

